### ISSUE TITLE
OffsetAreaChart width is incorrect

### ISSUE THREAD

**Issue by ericsoco** [americanpanorama/panorama-canals#3]
![screen shot 2016-01-11 at 12 13 45 pm](https://cloud.githubusercontent.com/assets/1127259/12246716/ead4e952-b864-11e5-81cd-793d1e72d559.png)

This problem started with the refactor removing Koto from `OffsetAreaChart` in `@panorama/toolkit`. Pegging `package.json` to [this commit](https://github.com/americanpanorama/panorama/commit/3b7aa538948042decad17ea234849af8b8bf2cb1) restores the original functionality.

@sconnelley and I discussed; looks like width/height are somehow not getting passed down into [`D3Component`](https://github.com/americanpanorama/panorama/blob/master/src/charts/D3Component.js#L74-L80) from [ChartSlider](https://github.com/americanpanorama/panorama/blob/master/src/ChartSlider/ChartSlider.jsx#L58-L61), via [`D3ReactBase`](https://github.com/americanpanorama/panorama/blob/master/src/charts/D3ReactBase.jsx#L29-L32).

**Comment by ebrelsford** [comment]
@ericsoco I'm trying to recreate this using `@panorama/toolkit#master` but here's what I see:

![canals-width](https://cloud.githubusercontent.com/assets/375002/14214558/aa1dc4a6-f80b-11e5-839d-7c9e51e2eea0.png)

Do you think this is resolved, or am I doing something incorrectly? I think I'm doing the `npm link` stuff right.

**Comment by ericsoco** [comment]
Crap. This is fixed, this is the other ticket I forgot to close when I updated/fixed the component. Sorry @ebrelsford!
