### ISSUE TITLE
Canal name text appearing in commodity box 

### ISSUE THREAD

**Issue by emilyhobson** [americanpanorama/panorama-canals#6]
![capture](https://cloud.githubusercontent.com/assets/824082/13266800/9e1adc3e-da2e-11e5-9eda-97c77481dd3f.PNG)

**Comment by ericsoco** [comment]
@emilyhobson where/when did you see this? In prod, or do you have a local build running?

**Comment by ericsoco** [comment]
Looks like this is happening in production? @jmadron did you actually deploy a new build? Might want to roll back.

**Comment by almccon** [comment]
We resolved this a day or two later, right @ericsoco and @jmadron? Is this safe to close?

**Comment by jmadron** [comment]
@almccon that is correct. We fixed this by using an older version of the toolkit. I think @ericsoco fixed the issue with the newest version shortly after.

**Comment by ericsoco** [comment]
All correct. Sorry I never closed this.
